/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as SupervisorRouteRouteImport } from './routes/supervisor/route'
import { Route as ExecRouteRouteImport } from './routes/exec/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor/index'
import { Route as ExecIndexRouteImport } from './routes/exec/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRouteRoute = SupervisorRouteRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecRouteRoute = ExecRouteRouteImport.update({
  id: '/exec',
  path: '/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const ExecIndexRoute = ExecIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exec': typeof ExecRouteRouteWithChildren
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/dispatch': typeof DispatchRoute
  '/admin/': typeof AdminIndexRoute
  '/exec/': typeof ExecIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dispatch': typeof DispatchRoute
  '/admin': typeof AdminIndexRoute
  '/exec': typeof ExecIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exec': typeof ExecRouteRouteWithChildren
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/dispatch': typeof DispatchRoute
  '/admin/': typeof AdminIndexRoute
  '/exec/': typeof ExecIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exec'
    | '/supervisor'
    | '/catalog'
    | '/dispatch'
    | '/admin/'
    | '/exec/'
    | '/supervisor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/dispatch' | '/admin' | '/exec' | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/exec'
    | '/supervisor'
    | '/catalog'
    | '/dispatch'
    | '/admin/'
    | '/exec/'
    | '/supervisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecRouteRoute: typeof ExecRouteRouteWithChildren
  SupervisorRouteRoute: typeof SupervisorRouteRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  DispatchRoute: typeof DispatchRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exec': {
      id: '/exec'
      path: '/exec'
      fullPath: '/exec'
      preLoaderRoute: typeof ExecRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/exec/': {
      id: '/exec/'
      path: '/'
      fullPath: '/exec/'
      preLoaderRoute: typeof ExecIndexRouteImport
      parentRoute: typeof ExecRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExecRouteRouteChildren {
  ExecIndexRoute: typeof ExecIndexRoute
}

const ExecRouteRouteChildren: ExecRouteRouteChildren = {
  ExecIndexRoute: ExecIndexRoute,
}

const ExecRouteRouteWithChildren = ExecRouteRoute._addFileChildren(
  ExecRouteRouteChildren,
)

interface SupervisorRouteRouteChildren {
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteRouteChildren: SupervisorRouteRouteChildren = {
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteRouteWithChildren = SupervisorRouteRoute._addFileChildren(
  SupervisorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecRouteRoute: ExecRouteRouteWithChildren,
  SupervisorRouteRoute: SupervisorRouteRouteWithChildren,
  CatalogRoute: CatalogRoute,
  DispatchRoute: DispatchRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
