/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteRouteImport } from './routes/supervisor/route'
import { Route as ExecRouteRouteImport } from './routes/exec/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor/index'
import { Route as ExecIndexRouteImport } from './routes/exec/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SupervisorVisitsRouteImport } from './routes/supervisor/visits'
import { Route as SupervisorRepsRouteImport } from './routes/supervisor/reps'
import { Route as SupervisorActivityRouteImport } from './routes/supervisor/activity'
import { Route as SupervisorAccountsRouteImport } from './routes/supervisor/accounts'
import { Route as AdminRepsRouteImport } from './routes/admin/reps'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'

const SupervisorRouteRoute = SupervisorRouteRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecRouteRoute = ExecRouteRouteImport.update({
  id: '/exec',
  path: '/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const ExecIndexRoute = ExecIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SupervisorVisitsRoute = SupervisorVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorRepsRoute = SupervisorRepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorActivityRoute = SupervisorActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorAccountsRoute = SupervisorAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const AdminRepsRoute = AdminRepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/exec': typeof ExecRouteRouteWithChildren
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reps': typeof AdminRepsRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/activity': typeof SupervisorActivityRoute
  '/supervisor/reps': typeof SupervisorRepsRoute
  '/supervisor/visits': typeof SupervisorVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/exec/': typeof ExecIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRoutesByTo {
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reps': typeof AdminRepsRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/activity': typeof SupervisorActivityRoute
  '/supervisor/reps': typeof SupervisorRepsRoute
  '/supervisor/visits': typeof SupervisorVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/exec': typeof ExecIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/exec': typeof ExecRouteRouteWithChildren
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reps': typeof AdminRepsRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/activity': typeof SupervisorActivityRoute
  '/supervisor/reps': typeof SupervisorRepsRoute
  '/supervisor/visits': typeof SupervisorVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/exec/': typeof ExecIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/exec'
    | '/supervisor'
    | '/admin/catalog'
    | '/admin/plans'
    | '/admin/quotes'
    | '/admin/reps'
    | '/supervisor/accounts'
    | '/supervisor/activity'
    | '/supervisor/reps'
    | '/supervisor/visits'
    | '/admin/'
    | '/exec/'
    | '/supervisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/catalog'
    | '/admin/plans'
    | '/admin/quotes'
    | '/admin/reps'
    | '/supervisor/accounts'
    | '/supervisor/activity'
    | '/supervisor/reps'
    | '/supervisor/visits'
    | '/admin'
    | '/exec'
    | '/supervisor'
  id:
    | '__root__'
    | '/admin'
    | '/exec'
    | '/supervisor'
    | '/admin/catalog'
    | '/admin/plans'
    | '/admin/quotes'
    | '/admin/reps'
    | '/supervisor/accounts'
    | '/supervisor/activity'
    | '/supervisor/reps'
    | '/supervisor/visits'
    | '/admin/'
    | '/exec/'
    | '/supervisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExecRouteRoute: typeof ExecRouteRouteWithChildren
  SupervisorRouteRoute: typeof SupervisorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exec': {
      id: '/exec'
      path: '/exec'
      fullPath: '/exec'
      preLoaderRoute: typeof ExecRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/exec/': {
      id: '/exec/'
      path: '/'
      fullPath: '/exec/'
      preLoaderRoute: typeof ExecIndexRouteImport
      parentRoute: typeof ExecRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/supervisor/visits': {
      id: '/supervisor/visits'
      path: '/visits'
      fullPath: '/supervisor/visits'
      preLoaderRoute: typeof SupervisorVisitsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/reps': {
      id: '/supervisor/reps'
      path: '/reps'
      fullPath: '/supervisor/reps'
      preLoaderRoute: typeof SupervisorRepsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/activity': {
      id: '/supervisor/activity'
      path: '/activity'
      fullPath: '/supervisor/activity'
      preLoaderRoute: typeof SupervisorActivityRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/accounts': {
      id: '/supervisor/accounts'
      path: '/accounts'
      fullPath: '/supervisor/accounts'
      preLoaderRoute: typeof SupervisorAccountsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/admin/reps': {
      id: '/admin/reps'
      path: '/reps'
      fullPath: '/admin/reps'
      preLoaderRoute: typeof AdminRepsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminRepsRoute: typeof AdminRepsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminRepsRoute: AdminRepsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExecRouteRouteChildren {
  ExecIndexRoute: typeof ExecIndexRoute
}

const ExecRouteRouteChildren: ExecRouteRouteChildren = {
  ExecIndexRoute: ExecIndexRoute,
}

const ExecRouteRouteWithChildren = ExecRouteRoute._addFileChildren(
  ExecRouteRouteChildren,
)

interface SupervisorRouteRouteChildren {
  SupervisorAccountsRoute: typeof SupervisorAccountsRoute
  SupervisorActivityRoute: typeof SupervisorActivityRoute
  SupervisorRepsRoute: typeof SupervisorRepsRoute
  SupervisorVisitsRoute: typeof SupervisorVisitsRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteRouteChildren: SupervisorRouteRouteChildren = {
  SupervisorAccountsRoute: SupervisorAccountsRoute,
  SupervisorActivityRoute: SupervisorActivityRoute,
  SupervisorRepsRoute: SupervisorRepsRoute,
  SupervisorVisitsRoute: SupervisorVisitsRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteRouteWithChildren = SupervisorRouteRoute._addFileChildren(
  SupervisorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExecRouteRoute: ExecRouteRouteWithChildren,
  SupervisorRouteRoute: SupervisorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
